; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed = 921600
upload_port = COM3

lib_deps = 
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
	Wire
lib_ignore = 
    FluxGarage RoboEyes
build_flags = 
	-Ilib/FluxGarage_RoboEyes
	-DROBODEFAULT=0
	-DTIRED=1
	-DANGRY=2
	-DHAPPY=3
	-DDEBOUNCE_DELAY=150
	-DLONG_PRESS_TIME=1000
	
